## 记录pytorch中一些常用到的函数

In [2]:
import torch


### *torch.unsqueeze()*  
在指定位置插入一个数值为1的维度

In [27]:
# 一维
a = torch.Tensor([1, 2, 3, 4])
print(a.shape)
a = a.unsqueeze(1)
print('-->', a.shape)
# 二维
a = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(a.shape)
a = a.unsqueeze(1)
print('-->', a.shape)


torch.Size([4])
--> torch.Size([4, 1])
torch.Size([2, 3])
--> torch.Size([2, 1, 3])


### *torch.squeeze()*  
删除指定位置的**数值为1**的维度

In [32]:
a = torch.Tensor([[[1, 2, 3]], [[4, 5, 6]]])
print(a, a.shape)
a = a.squeeze(1)
print(a, a.shape)


tensor([[[1., 2., 3.]],

        [[4., 5., 6.]]]) torch.Size([2, 1, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]]) torch.Size([2, 3])


### *torch.transpose()*  
交换两个维度

In [29]:
a = torch.Tensor([[[1, 2, 3], [4, 5, 6]]])
print(a, a.shape)
a = a.transpose(1, 2)
print('-->', a, a.shape)


tensor([[[1., 2., 3.],
         [4., 5., 6.]]]) torch.Size([1, 2, 3])
--> tensor([[[1., 4.],
         [2., 5.],
         [3., 6.]]]) torch.Size([1, 3, 2])
