# 自动微分

In [1]:
import torch

### 例子

In [2]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
x.requires_grad_(True)  # 等价于x=torch.arange(4.0,requires_grad=True)
x.grad  # 默认值是None

In [4]:
y = 2*torch.dot(x, x)  # y=2x^2
y

tensor(28., grad_fn=<MulBackward0>)

In [5]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [11]:
x.grad.zero_()  # PyTorch会累积梯度，需要手动清除之前的值
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

### 非标量变量的反向传播

In [19]:
x.grad.zero_()
y = x*x
y.sum().backward()  # 等价于y.backward(torch.ones(len(x)))
x.grad

tensor([0., 2., 4., 6.])

### 分离计算

In [26]:
x.grad.zero_()
y = x*x
u = y.detach()  # y作为常数
z = u*x
z.sum().backward()
x.grad

tensor([0., 1., 4., 9.])