# 数据操作

In [1]:
import torch

### arange(x): 从0开始创建一个长度为x的张量

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### shape()：张量的形状

In [3]:
x.shape

torch.Size([12])

### numel()：张量中元素的个数

In [4]:
x.numel()

12

### reshape()：改变张量的形状

In [5]:
X = x.reshape(3, 4)#可使用 x.reshape(-1,4) 或 x.reshape(3,-1) 替代
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### zeros() ones() ：创建元素全为0或1的张量

In [6]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

### randn()：根据正态分布创建张量

In [8]:
torch.randn(3,4)

tensor([[-0.0442, -1.4390, -0.2584, -0.1696],
        [-2.6017, -1.4791,  0.2987, -0.2523],
        [ 1.9547, -0.7268,  0.7200,  1.6115]])

### 张量的一些数学运算

In [9]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [10]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

## 对张量的一些操作

In [11]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X,Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

### 张量的索引与切片

In [12]:
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

### 单个或批量改变元素值

In [13]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [14]:
X[0:2,:] = 33
X

tensor([[33., 33., 33., 33.],
        [33., 33., 33., 33.],
        [ 8.,  9., 10., 11.]])

### 按维度拼接张量

In [15]:
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[33., 33., 33., 33.],
         [33., 33., 33., 33.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[33., 33., 33., 33.,  2.,  1.,  4.,  3.],
         [33., 33., 33., 33.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

### 两个张量相等：所有对应位置的元素值相等

In [16]:
X==Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

### sum()：张量中所有元素求和

In [17]:
X.sum()

tensor(302.)

### 广播机制：若两个张量形状不一致则先统一到同一个形状

In [18]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [19]:
# a复制了自己的列、b复制了自己的行
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 转换为其他Python对象

### 转换为Numpy数组

In [20]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

### 大小为1的张量转为Python标量

In [21]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)